{{- range .Values.pluginSecrets.oci.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.oci.auth.secretName is required!" .secretName }}
stringData:
  username: {{ required ".Values.pluginSecrets.oci.auth.username is required!" .username }}
  password: {{ required ".Values.pluginSecrets.oci.auth.password is required!" .password }}
---
{{- end }}
