{{- range .Values.pluginSecrets.network.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.network.auth[*].secretName is required!" .secretName }}
stringData:
  username: {{ required ".Values.pluginSecrets.network.auth[*].username is required!" .username | quote }}
  password: {{ required ".Values.pluginSecrets.network.auth[*].password is required!" .password | quote }}
{{- end }}
