{{- if .Values.pluginSecrets.azure }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.azure.secretName is required!" .Values.pluginSecrets.azure.secretName }}
stringData:
  {{- range $key, $val := .Values.pluginSecrets.azure.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}