{{- range .Values.pluginSecrets.network.caCerts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.network.caCerts[*].secretName is required!" .secretName }}
stringData:
  ca.crt: |
{{ required ".Values.pluginSecrets.network.caCerts[*].caCert is required!" .caCert | indent 4 }}
{{- end }}