{{- if .Values.pluginSecrets.aws }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.aws.secretName is required!" .Values.pluginSecrets.aws.secretName }}
stringData:
  {{- range $key, $val := .Values.pluginSecrets.aws.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}