{{- range .Values.pluginSecrets.oci.pubKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.oci.pubKeys.secretName is required!" .secretName }}
data:
 {{- range $key, $val := . }}
 {{- if hasSuffix ".pub" $key }}
 {{ $key }}: {{ $val | b64enc | quote }}
 {{- end }}
 {{- end }}
---
{{- end }}
