{{- if .Values.pluginSecrets.aws }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.aws.secretName is required!" .Values.pluginSecrets.aws.secretName }}
stringData:
  credentials: |
    [default]
    aws_access_key_id={{ required ".Values.pluginSecrets.aws.accessKeyId is required!" .Values.pluginSecrets.aws.accessKeyId }}
    aws_secret_access_key={{ required ".Values.pluginSecrets.aws.secretAccessKey is required!" .Values.pluginSecrets.aws.secretAccessKey }}
    {{- if .Values.pluginSecrets.aws.sessionToken }}
    aws_session_token={{ $.Values.pluginSecrets.aws.sessionToken }}
    {{- end }}
{{- end }}