{{- if .Values.pluginSecrets.maas }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.maas.secretName is required!" .Values.pluginSecrets.maas.secretName }}
stringData:
  MAAS_API_KEY: {{ required ".Values.pluginSecrets.maas.maasApiKey is required!" .Values.pluginSecrets.maas.maasApiKey | quote }}
{{- end }}
