{{- if .Values.pluginSecrets.maas }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.maas.secretName is required!" .Values.pluginSecrets.maas.secretName }}
stringData:
  {{ required ".Values.pluginSecrets.maas.tokenKey is required!" .Values.pluginSecrets.maas.tokenKey }}: {{ required ".Values.pluginSecrets.maas.apiToken is required!" .Values.pluginSecrets.maas.apiToken | quote }}
{{- end }}
