{{- range .Values.pluginSecrets.oci.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.pluginSecrets.oci.auth[*].secretName is required!" .secretName }}
stringData:
  {{- range $key, $val := .env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
