{{- if and .Values.proxy.enabled .Values.proxy.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.proxy.secretName is required!" .Values.proxy.secretName }}
stringData:
  ca.crt: |
{{ required ".Values.proxy.caCert is required!" .Values.proxy.caCert | indent 4 }}
{{- end }}