# permissions for end users to edit validationresults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: validationresult-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: validator
    app.kubernetes.io/part-of: validator
    app.kubernetes.io/managed-by: kustomize
  name: validationresult-editor-role
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - validationresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - validationresults/status
  verbs:
  - get
