apiVersion: validation.spectrocloud.labs/v1alpha1
kind: ValidatorConfig
metadata:
  labels:
    app.kubernetes.io/name: validatorconfig
    app.kubernetes.io/instance: validatorconfig-sample
    app.kubernetes.io/part-of: validator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: validator
  name: validatorconfig-sample
spec:
  # TODO(user): Add fields here
