{{- if .Values.valid8orPluginAws.enabled }}
apiVersion: validation.spectrocloud.labs/v1alpha1
kind: AwsValidator
metadata:
  name: {{ .Values.valid8orPluginAws.validator.name }}
spec:
  auth:
    secretName: {{ .Values.valid8orPluginAws.validator.auth.secretName }}
  {{- if .Values.valid8orPluginAws.validator.iamRules }}
  iamRules:
  {{- range .Values.valid8orPluginAws.validator.iamRules }}
  - iamPolicies:
    {{- range .statements }}
    - statements:
      - actions:
        {{- range .actions }}
        - {{ . | quote }}
        {{- end }}
        effect: Allow
        resource: {{ .resource | quote }}
      version: "2012-10-17"
    {{- end }}
    iamRole: {{ .iamRole }}
  {{- end }}
  {{- end }}
  {{- if .Values.valid8orPluginAws.validator.tagRules }}
  tagRules:
  {{- range .Values.valid8orPluginAws.validator.tagRules }}
  - key: {{ .key | quote }}
    expectedValue: {{ .expectedValue | quote }}
    region: {{ .region }}
    resourceType: {{ .resourceType }}
    arns:
    {{- range .arns }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
---
{{- if .Values.valid8orPluginAws.auth.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.valid8orPluginAws.validator.auth.secretName }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.valid8orPluginAws.auth.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.valid8orPluginAws.auth.secretKey | b64enc }}
{{- end }}
{{- end }}
