apiVersion: v2
name: valid8or
description: Monitor results created by valid8or plugins and upload them to a configurable sink
type: application
version: 0.0.5  # x-release-please-version
appVersion: "0.0.5"  # x-release-please-version
