controllerManager:
  kubeRbacProxy:
    args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.15.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    args:
    - --health-probe-bind-address=:8081
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: quay.io/spectrocloud-labs/validator
      tag: v0.0.13  # x-release-please-version
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 64Mi
    sinkWebhookTimeout: 30s
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP

# Optional sink configuration
sink: {}
  # type: slack
  # secretName: "slack-secret"
  # apiToken: ""
  # channelId: ""
  # By default, a secret will be created. Leave the above fields blank and specify 'createSecret: false' to use an existing secret.
  # WARNING: the existing secret must match the format used in sink-secret.yaml
  # createSecret: true

# Validation plugin charts
plugins:
- chart:
    name: validator-plugin-aws
    repository: "https://spectrocloud-labs.github.io/validator-plugin-aws"
    version: "v0.0.10"
  values: |-
    controllerManager:
      kubeRbacProxy:
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image:
          repository: gcr.io/kubebuilder/kube-rbac-proxy
          tag: v0.14.1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      manager:
        args:
        - --health-probe-bind-address=:8081
        - --leader-elect
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image:
          repository: quay.io/spectrocloud-labs/validator-plugin-aws
          tag: v0.0.8
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      replicas: 1
      serviceAccount:
        annotations: {}
    kubernetesClusterDomain: cluster.local
    metricsService:
      ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: https
      type: ClusterIP
    auth:
      # Leave secret undefined for implicit auth (node instance role, IMDSv2, etc.)
      secret: {}
        # secretName: aws-creds
        # accessKeyId: ""
        # secretAccessKey: ""
        # sessionToken: ""
        # By default, a secret will be created. Leave the above fields blank and specify 'createSecret: false' to use an existing secret.
        # WARNING: the existing secret must match the format used in auth-secret.yaml
        # createSecret: true
    
      # Override the service account used by AWS validator (optional, could be used for IMDSv2 on EKS)
      # WARNING: the chosen service account must have the same RBAC privileges as seen in manager-rbac.yaml
      serviceAccountName: ""
- chart:
    name: validator-plugin-vsphere
    repository: "https://spectrocloud-labs.github.io/validator-plugin-vsphere"
    version: "v0.0.12"
  values: |-
    controllerManager:
      kubeRbacProxy:
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image:
          repository: gcr.io/kubebuilder/kube-rbac-proxy
          tag: v0.14.1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      manager:
        args:
        - --health-probe-bind-address=:8081
        - --leader-elect
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image:
          repository: quay.io/spectrocloud-labs/validator-plugin-vsphere
          tag: v0.0.11
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      replicas: 1
      serviceAccount:
        annotations: {}
    kubernetesClusterDomain: cluster.local
    metricsService:
      ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: https
      type: ClusterIP
    auth:
      secretName: vsphere-creds
      username: ""
      password: ""
      vcenterServer: ""
      insecureSkipVerify: ""
- chart:
    name: validator-plugin-network
    repository: "https://spectrocloud-labs.github.io/validator-plugin-network"
    version: "v0.0.4"
  values: |-
    controllerManager:
      kubeRbacProxy:
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image:
          repository: gcr.io/kubebuilder/kube-rbac-proxy
          tag: v0.14.1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      manager:
        args:
        - --health-probe-bind-address=:8081
        - --leader-elect
        containerSecurityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_RAW
            drop:
            - ALL
        image:
          repository: quay.io/spectrocloud-labs/validator-plugin-network
          tag: v0.0.4
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      replicas: 1
      serviceAccount:
        annotations: {}
    kubernetesClusterDomain: cluster.local
    metricsService:
      ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: https
      type: ClusterIP
