name: Release

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'

jobs:
  call-release:
    uses: validator-labs/workflows/.github/workflows/release.yaml@main
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
    secrets: inherit

  haul:
    if: needs.call-release.outputs.releases_created == 'true'
    runs-on: [self-hosted, Linux, X64, validator]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: recursive

      - name: Generate Hauls for release
        run: make haul
      
      - name: Attach Hauls to release
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v2
        with:
          tag_name: ${{ needs.call-release.outputs.tag_name }}
          files: ./validator-haul-linux-amd64.tar.zst,./validator-haul-darwin-arm64.tar.zst